#!/usr/bin/env bash

# gloox has a memory leak in its TLS implementation so the only way to create
# reconnect functionality without a memory leak is to destroy the process
# between reconnects.

if [[ -z "$TYRION_NODE" ]]; then
    export TYRION_NODE="tyrion-node"
fi

if ! [[ "$TYRION_NODE_RESTART" =~ ^[0-9]+$ ]]; then
    export TYRION_NODE_RESTART="10"
fi

if [ $TYRION_NODE_RESTART -lt 1 ]; then
    export TYRION_NODE_RESTART="1"
fi

function runner {
    ARGS="$@"
    while [ true ]; do
        $TYRION_NODE $ARGS
        case "$?" in
            0)
                return 0
                ;;
            76)
                echo "Restarting in $TYRION_NODE_RESTART seconds..."
                sleep "$TYRION_NODE_RESTART" || return 1
                ;;
            *)
                return 1
                ;;
        esac
    done
}

runner $@ &
trap "kill $! &> /dev/null; exit" INT TERM
wait
