.TH REDIS-CLI 1 "July 28, 2010"
.SH NAME
redis-cli - Redis client
.SH SYNOPSIS
.PP
.B redis-cli
[-h host]
[-p port]
[-a authpw]
[-r repeat_times]
[-n db_num]
[-i]
arg1
arg2
.SH DESCRIPTION
.PP
This is a client for sending commands to Redis.
.SH OPTIONS
.TP
.B -h
Server hostname (default 127.0.0.1).
.TP
.B -p
Server port (default 6379).
.TP
.B -a
The authentication password.
.TP
.B -r
Send command multiple times.
.TP
.B -n
Redis database number.
.TP
.B -i
Start in interactive mode.
.SH "EXAMPLES"
cat /etc/passwd | redis-cli set my_passwd
.br
redis-cli get my_passwd
.br
redis-cli -r 100 lpush mylist x
.SH "AUTHOR"
.PP
Redis was written by Salvatore Sanfilippo.
.PP
This stub was created by Silas Sewell <silas@sewell.ch> for the Fedora Project.
.SH "SEE ALSO"
tyrion-benchmark(1), tyrion-stat(1)
