.TH REDIS-SERVER 8 "July 28, 2010"
.SH NAME
redis-server - Redis server
.SH SYNOPSIS
.PP
.B redis-server
<config-file>
.SH DESCRIPTION
.PP
This is the Redis server.
.SH "AUTHOR"
.PP
Redis was written by Salvatore Sanfilippo.
.PP
This stub was created by Silas Sewell <silas@sewell.ch> for the Fedora Project.
.SH "SEE ALSO"
redis-benchmark(1), redis-cli(1), redis-stat(1)
